// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, httpHandler *Handler) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chat/qianWen",
				Handler: httpHandler.QianWen.(),
			},
		},
	)
}
